GET http://localhost:3000/lembur/

###


POST http://localhost:3000/user/signin HTTP/1.1
Content-Type: application/json
{
    "email": "manager@gmail.com",
    "password": "manager"
}


###


POST http://localhost:3000/lembur/ HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbmFnZXJAZ21haWwuY29tIiwiaWQiOiI2MTNlYjJjOWY0MGQ0ZDRlY2MzY2YxY2EiLCJpYXQiOjE2MzE1MDY2NDAsImV4cCI6MTYzMTUxMDI0MH0.UALciPIUsoO05mdaRv9SHwXN78x-6jo7dlLANc0iYTQ
content-type: application/json

{
    "assignee": "613eb2def40d4d4ecc3cf1cd",
    "assigner": "Dwi Prasetyo",
    "reasons": "This is staff",
    "time": "2021-09-13",
    "startTime": "2021-09-13T17:00:00.000Z",
    "endTime": "2021-09-13T20:00:00.000Z"
}